name: Unzip and Commit

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Unzip file
        run: unzip -o truyenhobe.zip -d ./truyenhobe

      - name: Remove zip
        run: rm truyenhobe.zip

      - name: Commit unzipped files
        run: |
          git config --global user.email "truonganthanyeu2023@gmail.com"
          git config --global user.name "Ho Be"
          git add .
          git commit -m "Unzipped files"
          git push
